### ISSUE TITLE
Parameterize CosmosDB query with IN clause

### ISSUE THREAD

**Issue by avinash0310** [Azure/azure-cosmosdb-node#247]
I'm looking for any working way to parameterize IN clause in query.
I have tried something like this, But not working.
```
{      
    query: "Select r.id, r.Shipper.Name AS Shipper FROM root r WHERE r.Shipper.Name IN (@Shipper0, 
                 Shipper1)",     
    parameters: [          
        { name: "@Shipper0", value: "ABC" },
        { name: "@Shipper1", value: "XYZ" }     
    ] 
}
```
To create this "`(@Shipper0, @Shipper1)`", did some c# coding.
Without params same query working fine.
`List<string> list = new List<string>();`
Working query: ==> **`$"Select r.id, r.Shipper.Name AS Shipper FROM root r Where r.Shipper.Name IN ( '{string.Join("', '", list)}')";`**

Thanks "IN" advance.

**Comment by srinathnarayanan** [comment]
@bchong95 can you please take a look at this?

**Comment by gahoba** [comment]
Hello,
   Is this issue still open.  would like to know how this was resolved.

**Comment by southpolesteve** [comment]
@gahoba This issue is quite old so I don't know the history, but this works for me in the latest JS SDK:

``` js
client
  .database('database')
  .container('container')
  .items.query({
    query: 'Select * FROM root r WHERE r.team IN (@param1, @params2)',
    parameters: [
      { name: '@param1', value: 'bar' },
      { name: '@param2', value: 'foo' }
    ]
  })
  .fetchAll()
```

FYI one of our query team posted an answer on stack overflow that has some more details and a way to do this using ARRAY_CONTAINS https://stackoverflow.com/questions/44636971/where-in-with-azure-documentdb-cosmosdb-net-sdk/44639998#44639998

If you run into other issues, please open them over in our [central SDK repo](https://github.com/Azure/azure-sdk-for-js) as this repo is no longer maintained
